#define TRIVOX_MIN_LVL                   0
#define TRIVOX_MAX_LVL                   3
#define TRIVOX_MAX_TOTAL_SHAPE_UVS       1024
#define TRIVOX_MAX_TOTAL_SHAPE_MATERIALS 256
#define TRIVOX_MAX_TOTAL_CELLS           65536
#define TRIVOX_MAX_SHAPES_PER_ROOM       256
#define TRIVOX_MAX_VERTS_PER_SHAPE       3
#define TRIVOX_MAX_ROOMS                 16
#define TRIVOX_MAX_ENTITIES              256
#define TRIVOX_ENTITY_MAX_PARAMS         8
#define TRIVOX_MAX_TOTAL_SHAPES          TRIVOX_MAX_SHAPES_PER_ROOM * TRIVOX_MAX_ROOMS
#define TRIVOX_MAX_TOTAL_SHAPE_CELL_REFS TRIVOX_MAX_TOTAL_CELLS * TRIVOX_MAX_SHAPES_PER_ROOM
#define TRIVOX_MAX_TOTAL_VERTS           TRIVOX_MAX_VERTS_PER_SHAPE * TRIVOX_MAX_TOTAL_SHAPES